### ISSUE TITLE
Training your own data set

### ISSUE THREAD

**Issue by aaseagrass** [mithi/vehicle-tracking-2#1]
Hello. Currently new to python and working in our senior's project. I find this HOG suited in our objectives with the integration of svm. But my main problem is how I would able to train our own dataset. can you give us idea on how to train our own datasets? Thank you!

**Comment by mithi** [comment]
@aaseagrass 

Use the code in the notebook below, replace to target own directories. Don't forget that each png image should be resized to 64 pixels x 64 pixels. 

https://github.com/mithi/vehicle-tracking-2/blob/master/ipynb/classifier_training.ipynb
